### ISSUE TITLE
Information & Inspiration

### ISSUE THREAD

**Issue by fallengravity** [Asymetrex/desktop-app#1]
-- Charts --

Use: https://chart.asymetrex.com?ticker=<target><base>
Example: https://chart.asymetrex.com?ticker=monbtc
Implementation: Iframe

(If the Source Code is needed let me know)

-- Market Page --

Style: 
![Screenshot 2020-04-19 at 11 18 13](https://user-images.githubusercontent.com/37632291/79684161-8a161c00-822f-11ea-9c9b-8a553d442a7a.png)

I'd like the market table to look similar to this - We can ditch the graph section from the screenshot, the market table in-app must have the same columns/headings as the table on https://asymetrex.com/markets

-- Wallets Page --

I'd like the deposit section to look something similar to this deposit page:
![image](https://user-images.githubusercontent.com/37632291/79684472-f7c34780-8231-11ea-94be-1f745351aa97.png)

I'd like the withdraw section to look something similar to this page there should be 2 card per row - Card:

![Screenshot 2020-04-19 at 11 48 24](https://user-images.githubusercontent.com/37632291/79684710-c21f5e00-8233-11ea-91e3-d367476b7bf3.png)

2 per row:
![Screenshot 2020-04-19 at 11 49 22](https://user-images.githubusercontent.com/37632291/79684718-d5cac480-8233-11ea-9113-249ddfe7f1cf.png)

**Comment by newCodeRunner** [comment]
Please check the draft layout and propose any changes/style variations.

Card table on the landing page is not responsive yet, it will be made responsive (show hide columns according to screen size)
[spa.zip](https://github.com/Asymetrex/desktop-app/files/4532761/spa.zip)

**Comment by fallengravity** [comment]
Hey, Looks great so far! 

A couple of things: 

1.) ETHO Markets can be removed since it won't work via the API.
2.) Please change "Buy" on the button to Trade.
3.) Would be possible to make the table using 100% of the space? I've attached an image of space   I see (But it might be because of the page not yet being responsive I'm not sure.
![Screenshot 2020-04-25 at 12 23 13](https://user-images.githubusercontent.com/37632291/80277497-9dbdf880-86ef-11ea-8c8f-cce6959b7851.png)

Otherwise, I'm very happy with your work 👍

**Comment by newCodeRunner** [comment]
Hey thanks for the fast response. Am in a weekend sprint mood. :)
And am glad that you are liking it so far.

Please see my remarks below:

1.) ETHO Markets can be removed since it won't work via the API.
Okay, no problem.

2.) Please change "Buy" on the button to Trade.
Okay, no problem.

3.) Would be possible to make the table using 100% of the space? I've attached an image of space I see (But it might be because of the page not yet being responsive I'm not sure.

Yes, its cause i haven't added any responsiveness yet, Will do it of course. I propose that I move onto the electron source code, since it would be faster to check responsiveness on the only target electron app. Once I have completed the app, i will move onto linking the api.

Please let me know if you do not agree.

**Comment by fallengravity** [comment]
I'm happy with that. Just another few questions:

Are we able to support OTA Updates using GitHub releases?
Did you add i18n support? (Sorry, I haven't looked at the code at all since I made that commit)
Is there any way we can use something like Google analytics in the electron app?

**Comment by newCodeRunner** [comment]
Yes we can push updates by incorporating an auto update feature in electron-app using github releases.

No i didnt add i18n support yet. What languages do you want me to target?

Some questions from my side (since i havent studied or tested the api in detail - would help if you could answer briefly):

Landing Page
1. I have added virtual scroll onto the table considering there will be around 100 rows on each tab? to boost performance, the real site only shows 14, so virtual scroll can be removed if the rows are going to be less, (smaller build size)

2. How much data are we talking about? can it be fetched from server in 1 go? or do we need to incorporate lazy scroll loading.

3. Does the data in this table need to auto update based on web sockets?

Wallet Page
1. What size do you need for the QR Code? Currently it just takes the size of source image.

Nav Drawer:
1. Do you need to add external links (redirecting to your site for profile changes)?

Trusted Sites URLs
1., Can you provide me the URLs of trusted sites (origins only) from where the data would be fetched. This would allow me to force all other links and redirect urls to be opened in browser.
Not necessary, but recommended to provide your users an extra layer of security.

Wallet and trade pages:
Did you see these? is there anything else you would want to change at the moment?

Desktop Push Notifications:
Do you want an option where push notifications can pushed to users if they are logged in? like a special offer or best rate alert?

**Comment by fallengravity** [comment]
For i18n - Just English is perfect, we just need to be able to add translations on the fly with i18n.

Landing Page: 

1.) Markets are added every time we add a new coin, we're nowhere near 100 yet and our largest markets only have 14 pairs currently, however on our API we have a markets endpoint which outputs all our markets - https://asymetrex.com/api/markets - you could use that to determine how many rows you need.

2.) For populating the table with data I think it's safe to say it can be fetched in one go from the API for reference here's the API endpoint for that data https://asymetrex.com/api/tickers/ethobtc

3. I'd recommend refreshing that data every 2 minutes or so.

Wallet Page: 

1.) If you could make the QR code that same size as the box containing the wallet info on the right-hand side so that they line up that'd be great, by my estimation it looks like the height of 125px, and then width can be the same. An easier way to get QR codes is to use `https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl=ADDRESS`

Example:
<img src="https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl=0xefa3DbfDD4d9a14B9F0dc3F6c06582C7eAfe3066 />

Nav Drawer:

1.) Yes any profile changes will need to be done via the site as well as the generation of API keys.

**Comment by fallengravity** [comment]
Trusted Sites URLs:

https://asymetrex.com/api
https://chart.asymetrex.com

Wallet and trade pages:

On the trade page would you be able to add a small gap between the Buy order & Sell Order box. So that they don't merge into one:

![Screenshot 2020-04-25 at 13 15 37](https://user-images.githubusercontent.com/37632291/80278493-078dd080-86f7-11ea-8fe5-5e5e3e55494c.png)

Wallet page I'd also like a small gap between each card above + in the row

Apart from that, I'm happy with the work done so far.

As for push notifications that would be an awesome feature, so if you could add them I'd be extremely grateful.

**Comment by newCodeRunner** [comment]
All Done in release 0.0.3. You can event test the auto update, it should work now.
