### ISSUE TITLE
Final Updates & Changes

### ISSUE THREAD

**Issue by fallengravity** [Asymetrex/desktop-app#6]
1.) Buy and Sell boxes - there seems to be a bit of a UX issue with having to choose the button to open buy/sell orders.

2.) Canceling and seeing your orders - Currently, if the user wishes to cancel their order they have to visit the website to do so, this makes the experience unfriendly. Please can you implement API.orders & API.cancelOrder so this can be done in-app.

I think it'd be the best solution for both problems to copy Asymetrex's web version from implementing orders and fixing the UX.

Here's a screenshot of how I would like it to look - you can place it underneath the chart in a row with col-12:

![Screenshot 2020-05-14 at 08 49 27](https://user-images.githubusercontent.com/37632291/81902492-7d7fac00-95c0-11ea-8150-f1022aeb78bc.png)

in the screenshot below, you can see the user has a 'wait' order (An order which is yet to be executed):

![Screenshot 2020-05-14 at 08 55 13](https://user-images.githubusercontent.com/37632291/81902715-e6ffba80-95c0-11ea-8a2b-ea3edd889a71.png)

The API call is like this (Market eg: xerobtc):
```
API.orders('market', (result) => {
    console.log(result);
  }, 'wait', 50, 1, 'desc');
```

Here's a proper example with a result:
```
API.orders('xerobtc', (result) => {
    console.log(result);
  }, 'wait', 50, 1, 'desc');

----

[ { id: 1679,
    side: 'sell',
    ord_type: 'limit',
    price: '0.00000002',
    avg_price: '0.0',
    state: 'wait',
    market: 'xerobtc',
    time: '2020-05-14T13:55:08+08:00',
    volume: '2849564.42744598',
    remaining_volume: '2849564.42744598',
    executed_volume: '0.0',
    trades_count: 0 } ]
```

to cancel order its:

```
API.cancelOrder(1829);
```

Example with Result:

```
API.cancelOrder(1679, (result) => {
console.log(result)
}) ;
```

This will return the order details if successfully deleted.

For the new box where the user can cancel orders there are only 5 things which need to display:
id, type (side), price, remaining_volume, and a cancel button for that order. 

The screenshot below is to give you an idea of what it should look like

![Screenshot 2020-05-14 at 08 55 13](https://user-images.githubusercontent.com/37632291/81903530-2b3f8a80-95c2-11ea-8773-a192e0330053.png)

Once we get this sorted out we should be good to do some final testing and pay you.

**Comment by fallengravity** [comment]
Great work, you've honestly exceeded my expectations.

**Comment by newCodeRunner** [comment]
Hi again,

Everything is done. It was a pleasure working with you.

**Comment by newCodeRunner** [comment]
Waiting for details so that i can correct it.

**Comment by fallengravity** [comment]
Hey mate, the data in the screenshot below should be fetched using the API.orders method:

![Screenshot 2020-05-15 at 14 36 50](https://user-images.githubusercontent.com/37632291/82051151-a59f0600-96b9-11ea-8111-1a8f0f24fde5.png)

So for example on the xerobtc market it would be:
```
API.orders('xerobtc', (result) => {
    console.log(result);
  }, 'wait', 50, 1, 'desc');
```
on the ethobtc market it should be: 
```
API.orders('ethobtc', (result) => {
    console.log(result);
  }, 'wait', 50, 1, 'desc');
```

Also then when the user double clicks an order to cancel it, it should use that orders id

**Comment by newCodeRunner** [comment]
Hi again, sorry for that, it is my bad. i had hard coded some dummy data to test DOM since i wasn't able to create any order (3 tries were over) and forgot to clean it up. (Didn't realize some orders would already be there on other currencies - Just noticed on a few)

Double clicking will bring only that order ID. already implemented that way. Please see below:
Order Appearing on XEROM-ETHO from 5th May
![image](https://user-images.githubusercontent.com/57590297/82065461-8e770d00-96e7-11ea-904a-98c69c2a8c24.png)

When double clicked it, cancel dialog catches the order ID, i have also Displayed ID now too (temporarily)
![image](https://user-images.githubusercontent.com/57590297/82065572-b36b8000-96e7-11ea-8dcf-25b4f435f96a.png)

Similarly for LiteCoin - BTC (on select box selection changed)
Active Box becomes:
![image](https://user-images.githubusercontent.com/57590297/82065708-e57ce200-96e7-11ea-9c3c-5a23a6dace05.png)

Clicking on top row
![image](https://user-images.githubusercontent.com/57590297/82065754-f4639480-96e7-11ea-8eb0-3d9f4a96dd61.png)

clicking on bottom row
![image](https://user-images.githubusercontent.com/57590297/82065872-1826da80-96e8-11ea-8b85-b4d2def02aa9.png)

**Comment by newCodeRunner** [comment]
Sorry for the inconvenience, I have pushed both a commit and release to fix this.

Also, i know its tough to test in detail in such a short time, so take your time. if you find further bugs, do contact me. and i will push updates, no problem!

PS. thanks for releasing payment.

Also cancelled one order from LiteCoin - BTC to test and it works
![image](https://user-images.githubusercontent.com/57590297/82066731-3e994580-96e9-11ea-89c5-9540d302aa43.png)
